[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "seisforge"
version = "0.2.0"
description = "A Python toolkit for seismic processing and analysis"
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "Mengjie Zheng", email = "mengjie.zheng96@outlook.com"}]
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pandas",
    "obspy",
    "xarray",
    "h5netcdf",
    "h5py",
    "joblib",
    "pyproj",
    "pyyaml"
]

[project.optional-dependencies]
dev = [
    "disba",
    "pytest",
    "ruff",
]
inv = [
    "disba",
]
hvsr = [
    "disba",
]
hvsr-fortran = [
    "disba",
    "meson>=1.3",
    "ninja",
]
gmt = [
    "pygmt",
]

[project.scripts]
seisforge = "seisforge.cli.main:main"
rfqc = "seisforge.rf.qc:main"
hkseq = "seisforge.rf.hk:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"seisforge.hvsr" = [
    "_fortran_src/*.f90",
    "_fortran_src/.f2py_f2cmap",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.ruff]
line-length = 88
src = ["src", "tests"]
